version: '3'

services:
  rasa-actions:
    image: rasa-actions
    container_name: "rasa-actions"
    ports:
      - 5055:5055
    build:
      context: rasa_bot
      dockerfile: actions.Dockerfile
  rasa:
    image: rasa
    container_name: "rasa_server"
    ports:
      - 5005:5005
    build:
      context: rasa_bot
      dockerfile: rasa.Dockerfile
  django:
    image: django
    container_name: "django_server"
    ports:
      - 8000:8000
    build:
      context: django_app
      dockerfile: django.Dockerfile


# Command to run : 
# docker compose -f "docker-compose.yml" up -d --build